server:
  port: 8761

spring:
  datasource:
    patient:
      url: jdbc:mysql://localhost:3306/patient_db
      username: root
      password: 25051999
      driver-class-name: com.mysql.cj.jdbc.Driver
    appointment:
      url: jdbc:mysql://localhost:3306/appointment_db
      username: root
      password: 25051999
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      netflix:
        discovery: DEBUG
